version: "3"

services:
  api:
    depends_on: 
    - db
    image: nghianinhnb/api
    container_name: api
    networks:
      - net
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_PORT: 3306
      DB_NAME: vdt
      DB_DIALECT: mysql
      DB_POOL_MIN: "1"
      DB_POOL_MAX: "5"
      DB_POOL_ACQUIRE: "30000"
      DB_POOL_IDLE: "10000"
    privileged: true

  web:
    image: nghianinhnb/web
    container_name: web
    networks:
      - net
    ports:
      - "3000:3000"
    privileged: true
  
  db:
    image: mysql:8.0.27
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vdt
    ports:
      - "3306:3306"

networks:
  net: